{% set name = "trove-classifiers" %}
{% set version = "2024.10.14" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pypa/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: e57a5cfa85a5995234b887069fc040fe7f7a628b8f4322f51d60b640162d5ea9

build:
  skip: true  # [py<38]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python
    - calver 2022.6.26
    - pip
    - setuptools
    - wheel
  run:
    - python

test:
  imports:
    - trove_classifiers
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pypa/trove-classifiers
  summary: Canonical source for classifiers on PyPI (pypi.org).
  description: |
    Canonical source for classifiers on PyPI.
    Classifiers categorize projects per PEP 301.
    Use this package to validate classifiers in packages for PyPI upload or download.
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  dev_url: https://github.com/pypa/trove-classifiers
  doc_url: https://pypi.org/project/trove-classifiers/

extra:
  recipe-maintainers:
    - xylar
