{% set name = "trove-classifiers" %}
{% set version = "2023.2.20" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/trove-classifiers-{{ version }}.tar.gz
  sha256: 860b0c0d8c9e0d32629ca5ef137ea1e637580b634b74ba40e1539fd34464c0f5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - calver
    - pip
  run:
    - python >=3.6

test:
  imports:
    - trove_classifiers
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pypa/trove-classifiers
  summary: Canonical source for classifiers on PyPI (pypi.org).
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xylar
