{% set name = "trove-classifiers" %}
{% set version = "2024.7.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 8328f2ac2ce3fd773cbb37c765a0ed7a83f89dc564c7d452f039b69249d0ac35

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - calver
    - pip
    - setuptools
  run:
    - python >=3.7

test:
  imports:
    - trove_classifiers
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pypa/trove-classifiers
  summary: Canonical source for classifiers on PyPI (pypi.org).
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  dev_url: https://github.com/pypa/trove-classifiers
  doc_url: https://github.com/pypa/trove-classifiers/blob/main/README.md

extra:
  anaconda-services:
    reason: Dependency for apache-airflow
    recipe-maintainers:
      - ianaobi
  recipe-maintainers:
    - xylar
