{% set name = "trove-classifiers" %}
{% set version = "2023.3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/trove-classifiers-{{ version }}.tar.gz
  sha256: ee42f2f8c1d4bcfe35f746e472f07633570d485fab45407effc0379270a3bb03

build:
  skip: true  # [py<38]
  script: {{ PYTHON }} -m pip install . -vv --no-deps
  number: 0

requirements:
  host:
    - python
    - calver 2022.6.26
    - pip
    - setuptools
    - wheel
  run:
    - python

test:
  imports:
    - trove_classifiers
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pypa/trove-classifiers
  summary: Canonical source for classifiers on PyPI (pypi.org).
  description: | 
    Canonical source for classifiers on PyPI. 
    Classifiers categorize projects per PEP 301. 
    Use this package to validate classifiers in packages for PyPI upload or download.
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  dev_url: https://github.com/pypa/trove-classifiers
  doc_url: https://pypi.org/project/trove-classifiers/

extra:
  recipe-maintainers:
    - xylar
